server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://106.55.28.228:3306/db1?serverTimezone=UTC
      username: root
      password: 12345678
