server:
  port: 80
  servlet:
    context-path: /chatroom
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://106.55.28.228:3306/db1?serverTimezone=UTC
      username: root
      password: 12345678

mybatis-plus:
  mapper-locations: classpath:cc/nozuch/mapper/**.xml